name: Deploy

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  check-comment:
    if: github.event.comment.body == '/deploy'
    uses: ./.github/workflows/preview.yaml
    permissions:
      id-token: write
      contents: write
      pages: write
      pull-requests: write
