name: preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed # This is not part of the default and is the reason we explicitly specify the activity types. This is so that rossjrw/pr-preview-action gets triggered on close, which will tear down the preview app.
    paths:
      - react-playground/**
  workflow_dispatch: {}

concurrency:
  group: preview-${{ github.head_ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write
  pages: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install and Build
        if: github.event.action != 'closed' # You might want to skip the build if the PR has been closed
        run: |
          pnpm -F react-playground i --frozen-lockfile
          CI=false pnpm -F react-playground build
        env:
          VITE_IMAGE_RELATIVE_PATH: '"."'
          VITE_PREVIEW: '"preview"'
          VITE_PR_NUMBER: '"${{ github.event.pull_request.number }}"'
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      - name: Deploy preview
        id: deploy-preview
        uses: rossjrw/pr-preview-action@v1.6.0
        with:
          source-dir: ./react-playground/dist/
          comment: false
      - name: Log deploy-preview outputs
        run: |
          echo "steps=${{ toJSON(steps) }}"
          echo "deployment_status=${{ env.deployment_status }}"
      - name: Comment on PR for preview
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        if: steps.deploy-preview.outputs.deployment_action == 'deploy' && env.deployment_status == 'success'
        with:
          header: pr-preview
          message: |
            [PR Preview Action](https://github.com/rossjrw/pr-preview-action) ${{ steps.deploy-preview.outputs.action-version }}
            :---:
            | <p></p> :rocket: View preview at <br> ${{ steps.deploy-preview.outputs.preview-url }} <br><br>
            | <h6>Built to branch [`${{ env.BRANCH_NAME }}`](${{ github.server_url }}/${{ github.repository }}/tree/${{ env.BRANCH_NAME }}) at ${{ steps.deploy-preview.outputs.action-start-time }}. <br> Preview will be ready when the [GitHub Pages deployment](${{ github.server_url }}/${{ github.repository }}/deployments) is complete. <br><br> </h6>
